#!/bin/bash

#requesting one node
#SBATCH -N1
#requesting 1 core
#SBATCH -n1
#SBATCH --mail-user=lorne.whiteway@star.ucl.ac.uk
#SBATCH --mail-type=FAIL
#SBATCH --job-name=glimpse
#SBATCH --time=2:00:00
########SBATCH --output=/share/splinter/ucapwhi/glimpse_project/logs/log.txt
#SBATCH --mem-per-cpu=24000

### Call this with a command line such as 'sbatch --array=0-9 ./job_script_create_cutouts'

eval "$(/share/apps/anaconda/3-2019.07/bin/conda shell.bash hook)"
conda activate /share/splinter/ucapwhi/conda/
srun /share/splinter/ucapwhi/glimpse_project/scripts/utility.py ${SLURM_ARRAY_TASK_ID}
