#!/bin/tcsh

#requesting one node
#SBATCH -N1
#requesting 1 core
#SBATCH -n1
#SBATCH --mail-user=lorne.whiteway@star.ucl.ac.uk
#SBATCH --mail-type=FAIL
#SBATCH --job-name=glimpse
#SBATCH --time=4:00:00
########SBATCH --output=/share/splinter/ucapwhi/glimpse_project/logs/log.txt
#SBATCH --mem-per-cpu=12000


source /share/splinter/ucapwhi/glimpse_project/set_environment.csh
srun /share/splinter/ucapwhi/glimpse_project/scripts/glimpse_caller.py ${SLURM_ARRAY_TASK_ID}
