#!/bin/tcsh

#requesting one node
#SBATCH -N1
#requesting 1 core
#SBATCH -n1
#SBATCH --mail-user=lorne.whiteway@star.ucl.ac.uk
#SBATCH --mail-type=FAIL
#SBATCH --job-name=glimpse
#SBATCH --time=36:00:00
#SBATCH --mem-per-cpu=12000

### Call this with a command line such as 'sbatch ../../scripts/job_script_merge_caller'

source /share/splinter/ucapwhi/glimpse_project/set_environment.csh
srun /share/splinter/ucapwhi/glimpse_project/scripts/glimpse_on_curved_sky.py -d . -t merge

